In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/Advertising.csv')

In [ ]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [ ]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [ ]:
X = df.drop('sales',axis=1)
y = df['sales']

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly_converter = PolynomialFeatures(degree=3,include_bias=False)

In [ ]:
poly_features = poly_converter.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train=scaler.transform(X_train)

In [ ]:
X_test = scaler.transform(X_test)

In [ ]:
# Ridge regression
from sklearn.linear_model import Ridge

In [ ]:
ridge = Ridge(alpha=10)

In [ ]:
ridge.fit(X_train,y_train)

Ridge(alpha=10)

In [ ]:
test_predictions = ridge.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [ ]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE=np.sqrt(MSE)

In [ ]:
MAE

0.5774404204714163

In [ ]:
RMSE

0.894638646131965

In [ ]:
MAE = mean_absolute_error(y_train,train_predictions)
MSE = mean_squared_error(y_train,train_predictions)
RMSE=np.sqrt(MSE)

In [ ]:
train_predictions = ridge.predict(X_train)

In [ ]:
MAE

0.5288348183025309

In [ ]:
RMSE

0.8491805208255244

In [ ]:
from sklearn.linear_model import RidgeCV

In [43]:
ridgecv=RidgeCV(alphas=(0.1,1,10),scoring='neg_mean_absolute_error')

In [ ]:
# prompt: give me  a list of scorer metrices

from sklearn.metrics import get_scorer_names

scorer_names = get_scorer_names()
scorer_names

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'd2_absolute_error_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_max_error',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'neg_root_mean_squared_log_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 're

In [42]:
#help(RidgeCV)

In [44]:
ridgecv.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_absolute_error')

In [45]:
ridgecv.alpha_

0.1

In [46]:
test_predictions=ridgecv.predict(X_test)

In [47]:
MAE=mean_absolute_error(y_test,test_predictions)
MSE=mean_squared_error(y_test,test_predictions)
RMSE=np.sqrt(MSE)

In [48]:
MAE

0.427377488434534

In [49]:
RMSE

0.6180719926938822

In [50]:
ridgecv.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [51]:
from sklearn.linear_model import LassoCV

In [52]:
lassocv=LassoCV(eps=0.1,n_alphas=100,cv=5,max_iter=1000)

In [53]:
lassocv.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [54]:
lassocv.alpha_

0.4943070909225831

In [55]:
test_predictions=lassocv.predict(X_test)

In [56]:
MAE=mean_absolute_error(y_test,test_predictions)
MSE=mean_squared_error(y_test,test_predictions)
RMSE=np.sqrt(MSE)

In [57]:
MAE

0.6541723161252868

In [58]:
RMSE

1.1308001022762548

In [59]:
lassocv.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [60]:
#Elastic Net
from sklearn.linear_model import ElasticNetCV

In [65]:
elastic_model=ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1])

In [70]:
elastic_model.l1_ratio_

1.0

In [67]:
elastic_model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.870e+00, tolerance: 3.684e-01
  model = cd_fast.enet_coordinate_descent(


ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1])

In [69]:
elastic_model.l1_ratio_

1.0

In [71]:
elastic_model.alpha_

0.004943070909225831

In [72]:
elastic_model.coef_

array([ 4.56928806,  0.07566819,  0.18172079, -4.48979135,  4.59067331,
       -0.20804764, -0.        ,  0.09546681,  0.        ,  1.54242764,
       -0.85370412, -0.        ,  0.09038227, -0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ])

In [73]:
test_predictions=elastic_model.predict(X_test)

In [74]:
MAE=mean_absolute_error(y_test,test_predictions)
MSE=mean_squared_error(y_test,test_predictions)
RMSE=np.sqrt(MSE)

In [75]:
RMSE


0.6181813495739873